### ISSUE TITLE
Missing setting field subject_accepted_review_reminder 

### ISSUE THREAD

**Issue by hachacha** [BirkbeckCTP/janeway#1713]
**Describe the bug**
When attempting to edit the email subject for `accepted_review_reminder` and `default_review_reminder` there is adoes not exist error
![image](https://user-images.githubusercontent.com/1020384/88074995-2d840f00-cb46-11ea-92f0-544badf9e3c0.png)

the equivalent of doing
```
>>> Setting.objects.get(name='subject_accepted_review_reminder')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/jon/.virtualenvs/janeway/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/jon/.virtualenvs/janeway/lib/python3.6/site-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
core.models.DoesNotExist: Setting matching query does not exist.

```

**Also** the name is confusing as well (both are listed as Default Review Reminder)
![image](https://user-images.githubusercontent.com/1020384/88073957-cca80700-cb44-11ea-9583-cd4e8cd97a0b.png)
A better names would be 
Default Review Reminder
and 
Accepted Review Reminder
or just have one (?)
It has been further suggested by my colleagues that  the description should be changed to 
"to remind reviewers of a new request," the description should be "Notify reviewer of accepted request and remind them to review submission."

**Janeway version**
a58d982c

**To Reproduce**
1. Go to http://localhost:8000/journalname/manager/templates/
2. click edit subject on accepted_review_reminder or default_review_reminder

**Expected behavior**
You are able to edit the email subject for this template.

**Desktop (please complete the following information):**
 - Linux 

**Additional context**
To fix or update these, would it be just as simple as altering the janeway.json or journal_defaults.json and running update? Or would that also overwrite the value fields of some of these email templates per journal?
We would like to integrate these fixes as soon as possible so I can do a PR if that's the correct way of solving.

**Comment by ajrbyers** [comment]
For accepted_review_reminder and default_review_reminder subjects you just need to add new entries to journal_defaults.json called:

accepted_review_reminder_subject and default_review_reminder_subject

For the desciptions/pretty names a data migration will be required as well as making the changes in defaults.

**Comment by ajrbyers** [comment]
> or just have one (?)
The serve different purposes.

**Comment by ajrbyers** [comment]
> 
> 
> For accepted_review_reminder and default_review_reminder subjects you just need to add new entries to journal_defaults.json called:
> 
> subject_accepted_review_reminder and subjectdefault_review_reminder
> 
> For the desciptions/pretty names a data migration will be required as well as making the changes in defaults.

Just updated this because subject should be at the start not the end.

**Comment by ajrbyers** [comment]
Hey @hachacha we're going to fix this and add a test to check that all emails have subjects.

**Comment by hachacha** [comment]
@ajrbyers thank you!! I started on the json but I'll let you handle it

We also noticed that the `from_address` setting does not have a subject that can be edited, but should it? Is it an email?
![image](https://user-images.githubusercontent.com/1020384/88078401-6d4cf580-cb4a-11ea-9eda-3c05089dcb0f.png)

Would you like me to go through and work on some of the pretty_name duplicates? noticed another one here:
![image](https://user-images.githubusercontent.com/1020384/88078712-c6b52480-cb4a-11ea-8140-138b8c3946fb.png)

**Comment by ajrbyers** [comment]
> 
> 
> @ajrbyers thank you!! I started on the json but I'll let you handle it
> 
> We also noticed that the `from_address` setting does not have a subject that can be edited, but should it? Is it an email?
> ![image](https://user-images.githubusercontent.com/1020384/88078401-6d4cf580-cb4a-11ea-9eda-3c05089dcb0f.png)
> 
> Would you like me to go through and work on some of the pretty_name duplicates? noticed another one here:
> ![image](https://user-images.githubusercontent.com/1020384/88078712-c6b52480-cb4a-11ea-8140-138b8c3946fb.png)

from_address is an anomoly that probably should be a General setting. We an ignore it in this instance. If you notice any other dupes fire them on here and I will update the migration im writing.

**Comment by ajrbyers** [comment]
![image](https://user-images.githubusercontent.com/8321378/88080322-d185ae80-cb76-11ea-880d-0e9a58979eec.png)
From Address will display this message now.

**Comment by ajrbyers** [comment]
@hachacha can you take a look at src/core/migrations/0041_fix_reminder_name_description.py in https://github.com/BirkbeckCTP/janeway/commit/37c73aa4bdedac39985502da303c3343e51f1c54 I've fixed some that I found. We've also moved from_address to general.

**Comment by hachacha** [comment]
Thanks~ I was able to apply the migration and see that you updated some of the text in the migration file for 0041 but for some reason it doesn't seem as though it worked, at least on my machine.
I restarted the server a couple times and rolled back and ran again but still no luck.
![image](https://user-images.githubusercontent.com/1020384/88216824-a6a96200-cc2b-11ea-9e91-71afbc603e3b.png)

![image](https://user-images.githubusercontent.com/1020384/88216285-e885d880-cc2a-11ea-905e-741c6874d574.png)
I'm on 37c73aa4

I see that the email subjects were added in a later commit, should I pull from that one to see if the changes occur?

**Comment by ajrbyers** [comment]
Cheers Jon. Yes pull that and have a go. I ran the migration here and it
looked ok but may be something else at work. Will double check tomorrow.

**Comment by hachacha** [comment]
Now on 46487866
I ran .update.sh and the email subjects are up but the pretty_name and descriptions still have not updated...

**Comment by ajrbyers** [comment]
> Now on [4648786](https://github.com/BirkbeckCTP/janeway/commit/46487866d7c6a9e50b9af733bbb8df7be86997b8)
> I ran .update.sh and the email subjects are up but the pretty_name and descriptions still have not updated...

Damn! I'll take a look at this tomorrow!

**Comment by hachacha** [comment]
I re-ran the migration and put in some printouts to see if things were actually changing and then it worked somehow.
Literally changed nothing other than some print() commands <:‑|
This is officially closed, thank you for your help.

**Comment by ajrbyers** [comment]
Pychache maybe?
